// ===== Structured Lessons =====
// Each lesson teaches a spelling rule, shows examples, then practices.
// Designed for a 13-year-old with dyslexia — rules are explained simply and clearly.

const LESSONS = [
    // ============================
    //  UNIT 1: Silent Letters
    // ============================
    {
        id: "silent-e",
        unit: 1,
        title: "The Silent E Rule",
        icon: "🔇",
        color: "#6c5ce7",
        rule: "When a word ends in a silent E, the vowel before it says its name (long sound). The E is silent — you don't hear it, but it changes the whole word.",
        examples: [
            { without: "hop", with: "hope", explanation: "Short O becomes Long O" },
            { without: "kit", with: "kite", explanation: "Short I becomes Long I" },
            { without: "cap", with: "cape", explanation: "Short A becomes Long A" },
            { without: "cub", with: "cube", explanation: "Short U becomes Long U" },
        ],
        words: [
            { word: "climate", hint: "The typical weather of a region", syllables: ["cli", "mate"] },
            { word: "complete", hint: "Finished, with nothing missing", syllables: ["com", "plete"] },
            { word: "compete", hint: "To try to win against others", syllables: ["com", "pete"] },
            { word: "admire", hint: "To look up to someone with respect", syllables: ["ad", "mire"] },
            { word: "erate", hint: "A rate or ratio used in calculations", syllables: ["e", "rate"] },
            { word: "remote", hint: "Far away from cities or people", syllables: ["re", "mote"] },
            { word: "extreme", hint: "The highest or most intense level", syllables: ["ex", "treme"] },
            { word: "survive", hint: "To stay alive through something difficult", syllables: ["sur", "vive"] },
            { word: "investigate", hint: "To look into something carefully", syllables: ["in", "ves", "ti", "gate"] },
            { word: "demonstrate", hint: "To show how something works", syllables: ["dem", "on", "strate"] },
        ],
    },
    {
        id: "silent-letters",
        unit: 1,
        title: "Silent Letters (K, W, B, G)",
        icon: "🤫",
        color: "#a29bfe",
        rule: "English has many words with silent letters that you write but don't say. KN makes a N sound. WR makes a R sound. MB at the end makes a M sound. GN makes a N sound.",
        examples: [
            { without: "nife", with: "knife", explanation: "The K is silent in KN" },
            { without: "rite", with: "write", explanation: "The W is silent in WR" },
            { without: "clime", with: "climb", explanation: "The B is silent in MB" },
            { without: "naw", with: "gnaw", explanation: "The G is silent in GN" },
        ],
        words: [
            { word: "knowledge", hint: "What you know from learning", syllables: ["knowl", "edge"] },
            { word: "knuckle", hint: "The joint in your finger", syllables: ["knuck", "le"] },
            { word: "wreckage", hint: "The remains of something destroyed", syllables: ["wreck", "age"] },
            { word: "wrinkle", hint: "A crease or fold in something", syllables: ["wrin", "kle"] },
            { word: "plumber", hint: "Someone who fixes pipes and water systems", syllables: ["plumb", "er"] },
            { word: "thumb", hint: "The short wide finger on your hand", syllables: ["thumb"] },
            { word: "design", hint: "To plan and create something", syllables: ["de", "sign"] },
            { word: "foreign", hint: "From a different country", syllables: ["for", "eign"] },
            { word: "knight", hint: "A medieval warrior in armor", syllables: ["knight"] },
            { word: "wrestling", hint: "A sport where you grapple with an opponent", syllables: ["wres", "tling"] },
        ],
    },

    // ============================
    //  UNIT 2: Double Letters
    // ============================
    {
        id: "double-consonants",
        unit: 2,
        title: "The Doubling Rule",
        icon: "✌️",
        color: "#e17055",
        rule: "When adding -ing, -ed, or -er to a short vowel word that ends in one consonant, you double the last consonant. This keeps the vowel short. Example: run → running (not runing).",
        examples: [
            { without: "runing", with: "running", explanation: "Double the N to keep the short U" },
            { without: "siting", with: "sitting", explanation: "Double the T to keep the short I" },
            { without: "begining", with: "beginning", explanation: "Double the N to keep the short I" },
            { without: "stoping", with: "stopping", explanation: "Double the P to keep the short O" },
        ],
        words: [
            { word: "occurring", hint: "Happening or taking place", syllables: ["oc", "cur", "ring"] },
            { word: "beginning", hint: "The start of something", syllables: ["be", "gin", "ning"] },
            { word: "committed", hint: "Dedicated to doing something", syllables: ["com", "mit", "ted"] },
            { word: "permitted", hint: "Allowed to do something", syllables: ["per", "mit", "ted"] },
            { word: "forgetting", hint: "Losing a memory of something", syllables: ["for", "get", "ting"] },
            { word: "referring", hint: "Mentioning or pointing to something", syllables: ["re", "fer", "ring"] },
            { word: "submitted", hint: "Turned in or handed over", syllables: ["sub", "mit", "ted"] },
            { word: "equipped", hint: "Given the tools or gear needed", syllables: ["e", "quipped"] },
            { word: "controlling", hint: "Managing or directing something", syllables: ["con", "trol", "ling"] },
            { word: "preferred", hint: "Liked better than the alternatives", syllables: ["pre", "ferred"] },
        ],
    },
    {
        id: "double-or-not",
        unit: 2,
        title: "When NOT to Double",
        icon: "☝️",
        color: "#fab1a0",
        rule: "Don't double the consonant when the word ends in two consonants (jump → jumping), or when there are two vowels before the final consonant (rain → raining), or when the stress is NOT on the last syllable (open → opening).",
        examples: [
            { without: "jumpping", with: "jumping", explanation: "Ends in MP — two consonants, so don't double" },
            { without: "rainning", with: "raining", explanation: "Two vowels (AI) before N, so don't double" },
            { without: "openning", with: "opening", explanation: "Stress is on O-pen, not on -pen, so don't double" },
            { without: "enterring", with: "entering", explanation: "Stress is on EN-ter, not on -ter" },
        ],
        words: [
            { word: "listening", hint: "Paying attention to sounds", syllables: ["lis", "ten", "ing"] },
            { word: "happening", hint: "Taking place or occurring", syllables: ["hap", "pen", "ing"] },
            { word: "developing", hint: "Growing or building over time", syllables: ["de", "vel", "op", "ing"] },
            { word: "suffering", hint: "Experiencing pain or hardship", syllables: ["suf", "fer", "ing"] },
            { word: "offering", hint: "Giving or presenting something", syllables: ["of", "fer", "ing"] },
            { word: "remaining", hint: "What is left over", syllables: ["re", "main", "ing"] },
            { word: "appearing", hint: "Becoming visible or showing up", syllables: ["ap", "pear", "ing"] },
            { word: "reasoning", hint: "Thinking logically to reach a conclusion", syllables: ["rea", "son", "ing"] },
            { word: "containing", hint: "Holding something inside", syllables: ["con", "tain", "ing"] },
            { word: "discovering", hint: "Finding something new", syllables: ["dis", "cov", "er", "ing"] },
        ],
    },

    {
        id: "floss-rule",
        unit: 2,
        title: "The FLOSS Rule (ff, ll, ss, zz)",
        icon: "🦷",
        color: "#e17055",
        teachSlides: [
            {
                id: "intro",
                title: "What is the FLOSS Rule?",
                content: "Today we are going to learn a really useful spelling pattern called the FLOSS rule. It helps you know when to double the last letter of a word. Sometimes when you write a word, you might wonder: should I write one F or two? One S or two? The FLOSS rule gives you the answer! The word FLOSS itself follows this rule. F-L-O-S-S. Let's learn how it works.",
                diagram: null,
            },
            {
                id: "the-rule",
                title: "The Three Things to Check",
                content: "Here are the three things you check. First, is the word one syllable? That means one beat, like 'stuff' or 'press.' Second, does the word have a short vowel? Short vowels say their sound, not their name. Short A like in cat, short E like in bed, short I like in sit, short O like in hot, short U like in bus. Third, does the word end in F, L, S, or Z? If all three answers are yes, you double that last letter!",
                diagram: null,
            },
            {
                id: "short-vowels",
                title: "Quick Review: Short Vowels",
                content: "Let's make sure we know our short vowel sounds. Short A says 'ah' like in cat, hat, and map. Short E says 'eh' like in bed, red, and pet. Short I says 'ih' like in sit, hit, and big. Short O says 'oh' like in hot, pot, and mop. Short U says 'uh' like in bus, cup, and fun. These short vowel sounds are the key to the FLOSS rule. When you hear a short vowel before F, L, S, or Z, that is your signal to double!",
                diagram: null,
            },
            {
                id: "ff-pattern",
                title: "Double F — The FF Pattern",
                content: "When a one-syllable word has a short vowel and ends in the letter F, you double the F. Let's look at some examples. Stuff: one syllable, short U, ends in F, so we write stuff with two F's. Cliff: one syllable, short I, ends in F, so we write cliff with two F's. The same goes for bluff, sniff, stiff, scoff, and scuff. Every single one has a short vowel right before the double F. That short vowel is your signal!",
                diagram: {
                    type: "doubling",
                    base: "stu",
                    vowel: "u",
                    ending: "f",
                    doubled: "ff",
                    examples: ["stuff", "cliff", "bluff", "sniff", "stiff", "scoff", "scuff"],
                },
            },
            {
                id: "ff-tricky",
                title: "Double F — Watch Out!",
                content: "Here is a helpful tip: the word 'if' only has one F. Why? Because there is no consonant before the vowel. Very short words like 'if' and 'of' are exceptions. But most FLOSS words have a consonant blend before the vowel, like the 'st' in stuff or the 'cl' in cliff. When you see a bigger one-syllable word ending in F with a short vowel, double it! Try saying these out loud: staff, scuff, bluff. Hear that short vowel? Double the F.",
                diagram: null,
            },
            {
                id: "ll-pattern",
                title: "Double L — The LL Pattern",
                content: "The same rule works for the letter L. When a one-syllable word has a short vowel and ends in L, you double the L. Skill: one syllable, short I, ends in L, so we write skill with two L's. Spell: one syllable, short E, ends in L, so we write spell with two L's. The same goes for drill, grill, spill, chill, dwell, and skull. Every one of these follows the pattern: short vowel plus L equals double L.",
                diagram: {
                    type: "doubling",
                    base: "ski",
                    vowel: "i",
                    ending: "l",
                    doubled: "ll",
                    examples: ["skill", "spell", "drill", "grill", "spill", "chill", "skull"],
                },
            },
            {
                id: "ll-tricky",
                title: "Double L — Watch Out!",
                content: "Double L words are everywhere! Think about it: you spell, you grill food, you chill out, you use a skill. A good way to remember is to listen for that short vowel sound. Say 'skill' slowly: s-k-ih-ll. Hear the short I? That tells you to double the L. Now say 'spill' slowly: s-p-ih-ll. Same short I, same double L. If the vowel said its name instead, like in 'file' or 'mile,' you would NOT double. Short vowel equals double!",
                diagram: null,
            },
            {
                id: "ss-pattern",
                title: "Double S — The SS Pattern",
                content: "Now let's look at S. When a one-syllable word has a short vowel and ends in S, you double the S. Press: one syllable, short E, ends in S, so we write press with two S's. Grass: one syllable, short A, ends in S, so we write grass with two S's. Also look at cross, floss, glass, dress, chess, and bliss. They all have a short vowel right before the double S.",
                diagram: {
                    type: "doubling",
                    base: "pre",
                    vowel: "e",
                    ending: "s",
                    doubled: "ss",
                    examples: ["press", "grass", "floss", "cross", "glass", "dress", "chess"],
                },
            },
            {
                id: "ss-tricky",
                title: "Double S — Watch Out!",
                content: "Double S is probably the most common FLOSS pattern you will see. Think of words you use every day: mess, less, boss, toss, miss, kiss. They all follow the rule! Here is a fun trick: the word 'floss' itself has a double S. You floss your teeth, and the word floss reminds you of the whole rule. Also remember: words like 'bus' and 'yes' only have one S. They are short common words that are exceptions. But most one-syllable words with a short vowel before S will double it.",
                diagram: null,
            },
            {
                id: "zz-pattern",
                title: "Double Z — The ZZ Pattern",
                content: "Finally we have Z. When a one-syllable word has a short vowel and ends in Z, you double the Z. Buzz: one syllable, short U, ends in Z, so we write buzz with two Z's. Fizz: one syllable, short I, ends in Z, so we write fizz with two Z's. There are fewer double Z words than double F, L, or S words, but they follow the exact same rule. Buzz, fizz, fuzz, jazz, and whizz all have that short vowel plus double Z.",
                diagram: {
                    type: "doubling",
                    base: "bu",
                    vowel: "u",
                    ending: "z",
                    doubled: "zz",
                    examples: ["buzz", "fizz", "fuzz", "jazz", "whizz"],
                },
            },
            {
                id: "zz-tricky",
                title: "Double Z — Watch Out!",
                content: "Here is something cool about double Z words: they almost always have a buzzing sound! Say buzz, fizz, jazz. Hear how they all have that zzz sound? That buzzing is the Z being doubled. The word quiz is a tricky one because it has a short vowel and ends in Z, but some people spell it with just one Z. Most FLOSS Z words are short and fun: buzz like a bee, fizz like a soda, jazz like the music, fuzz like a peach. The Z doubles because of that short vowel right before it.",
                diagram: null,
            },
            {
                id: "exceptions",
                title: "When the Rule Does NOT Apply",
                content: "The FLOSS rule only works when three things are true: one syllable, short vowel, and ends in F, L, S, or Z. If any of those are missing, do not double! For example, 'leaf' has a long E, not a short vowel, so it is just one F. 'Goal' has a long O, so just one L. 'Base' has a long A, so just one S. Also, if a word has two syllables like 'until,' the rule does not apply. Remember: check all three things before you double.",
                diagram: null,
            },
            {
                id: "summary",
                title: "Remember: F-L-O-S-S",
                content: "Let's put it all together. The word FLOSS helps you remember the whole rule. F stands for ff. L stands for ll. The O in the middle reminds you the vowel must be short. S stands for ss. And the second S reminds you of zz. Three checks: one syllable, short vowel, ends in F, L, S, or Z. If all three are yes, double that last letter! You have learned the FLOSS rule. Now let's put it into practice!",
                diagram: { type: "floss-acronym" },
            },
        ],
        rule: "In a one-syllable word with a short vowel, when the word ends in F, L, S, or Z, you usually double that final consonant. Think FLOSS — the word itself follows the rule! Short vowel + F = ff (stuff). Short vowel + L = ll (fill). Short vowel + S = ss (miss). Short vowel + Z = zz (buzz). This doesn't apply to words ending in other consonants, or words with long vowels.",
        examples: [
            { without: "stuf", with: "stuff", explanation: "Short U + F → double the F (ff)" },
            { without: "fil", with: "fill", explanation: "Short I + L → double the L (ll)" },
            { without: "mes", with: "mess", explanation: "Short E + S → double the S (ss)" },
            { without: "buz", with: "buzz", explanation: "Short U + Z → double the Z (zz)" },
        ],
        words: [
            { word: "bluff", hint: "To pretend you have something you don't", syllables: ["bluff"] },
            { word: "cliff", hint: "A steep rock face", syllables: ["cliff"] },
            { word: "sniff", hint: "To breathe in quickly through your nose", syllables: ["sniff"] },
            { word: "stiff", hint: "Not easy to bend", syllables: ["stiff"] },
            { word: "scuff", hint: "To scratch or scrape your shoe on the ground", syllables: ["scuff"] },
            { word: "spell", hint: "To write or say the letters of a word in order", syllables: ["spell"] },
            { word: "skill", hint: "An ability you develop with practice", syllables: ["skill"] },
            { word: "drill", hint: "A tool for making holes, or to practice repeatedly", syllables: ["drill"] },
            { word: "chill", hint: "A cool or cold feeling", syllables: ["chill"] },
            { word: "skull", hint: "The bones that protect your brain", syllables: ["skull"] },
            { word: "press", hint: "To push firmly against something", syllables: ["press"] },
            { word: "glass", hint: "A see-through material used in windows", syllables: ["glass"] },
            { word: "cross", hint: "To go from one side to the other", syllables: ["cross"] },
            { word: "floss", hint: "Thread used to clean between your teeth", syllables: ["floss"] },
            { word: "dress", hint: "A piece of clothing, or to put clothes on", syllables: ["dress"] },
            { word: "chess", hint: "A strategy board game with kings and queens", syllables: ["chess"] },
            { word: "buzz", hint: "The sound a bee makes", syllables: ["buzz"] },
            { word: "fizz", hint: "The bubbling sound a soda makes", syllables: ["fizz"] },
            { word: "jazz", hint: "A style of music with lots of rhythm", syllables: ["jazz"] },
            { word: "fuzz", hint: "Soft fluffy stuff, like on a peach", syllables: ["fuzz"] },
        ],
    },

    // ============================
    //  UNIT 3: I Before E
    // ============================
    {
        id: "i-before-e",
        unit: 3,
        title: "I Before E (and the Exceptions)",
        icon: "🔀",
        color: "#00cec9",
        rule: "The classic rule: I before E, except after C, or when sounding like A as in 'neighbor' and 'weigh'. But there are many exceptions — some words just need to be memorized.",
        examples: [
            { without: "beleive", with: "believe", explanation: "I before E — standard rule" },
            { without: "recieve", with: "receive", explanation: "After C, it's E before I" },
            { without: "nieghbor", with: "neighbor", explanation: "Sounds like A, so E before I" },
            { without: "wierd", with: "weird", explanation: "Exception! Just memorize this one" },
        ],
        words: [
            { word: "achieve", hint: "To reach a goal through effort", syllables: ["a", "chieve"] },
            { word: "believe", hint: "To think something is true", syllables: ["be", "lieve"] },
            { word: "receive", hint: "To get something given to you", syllables: ["re", "ceive"] },
            { word: "deceive", hint: "To trick someone into believing something false", syllables: ["de", "ceive"] },
            { word: "perceive", hint: "To notice or become aware of something", syllables: ["per", "ceive"] },
            { word: "ceiling", hint: "The top surface inside a room", syllables: ["ceil", "ing"] },
            { word: "weird", hint: "Strange or unusual", syllables: ["weird"] },
            { word: "foreign", hint: "From a different country", syllables: ["for", "eign"] },
            { word: "protein", hint: "A nutrient that builds muscles", syllables: ["pro", "tein"] },
            { word: "sufficient", hint: "Enough to meet a need", syllables: ["suf", "fi", "cient"] },
        ],
    },

    // ============================
    //  UNIT 4: Prefixes
    // ============================
    {
        id: "prefixes-negative",
        unit: 4,
        title: "Prefixes: un-, dis-, mis-, in-",
        icon: "🔧",
        color: "#fdcb6e",
        rule: "A prefix is added to the beginning of a word to change its meaning. These prefixes usually mean 'not' or 'opposite'. UN- = not. DIS- = opposite. MIS- = wrong. IN- (also IM-, IL-, IR-) = not. The spelling of the base word never changes.",
        examples: [
            { without: "unhappy", with: "unhappy", explanation: "UN + happy = not happy" },
            { without: "disagree", with: "disagree", explanation: "DIS + agree = opposite of agree" },
            { without: "misspell", with: "misspell", explanation: "MIS + spell = spell wrong (keep both S's!)" },
            { without: "impossible", with: "impossible", explanation: "IM + possible = not possible (IN becomes IM before P)" },
        ],
        words: [
            { word: "unnecessary", hint: "Not needed", syllables: ["un", "nec", "es", "sar", "y"] },
            { word: "uncomfortable", hint: "Not feeling at ease", syllables: ["un", "com", "fort", "a", "ble"] },
            { word: "disappoint", hint: "To fail to meet someone's hopes", syllables: ["dis", "ap", "point"] },
            { word: "disappear", hint: "To vanish from sight", syllables: ["dis", "ap", "pear"] },
            { word: "disconnect", hint: "To break a connection", syllables: ["dis", "con", "nect"] },
            { word: "misunderstand", hint: "To understand something wrong", syllables: ["mis", "un", "der", "stand"] },
            { word: "misspell", hint: "To spell a word incorrectly", syllables: ["mis", "spell"] },
            { word: "impossible", hint: "Cannot be done", syllables: ["im", "pos", "si", "ble"] },
            { word: "irregular", hint: "Not following the normal pattern", syllables: ["ir", "reg", "u", "lar"] },
            { word: "independent", hint: "Not depending on others", syllables: ["in", "de", "pen", "dent"] },
        ],
    },
    {
        id: "prefixes-other",
        unit: 4,
        title: "Prefixes: re-, pre-, over-, under-",
        icon: "🔁",
        color: "#f9ca24",
        rule: "RE- = again or back. PRE- = before. OVER- = too much or above. UNDER- = too little or below. The base word stays the same — just attach the prefix.",
        examples: [
            { without: "rebuild", with: "rebuild", explanation: "RE + build = build again" },
            { without: "preview", with: "preview", explanation: "PRE + view = see before" },
            { without: "overcome", with: "overcome", explanation: "OVER + come = rise above" },
            { without: "underestimate", with: "underestimate", explanation: "UNDER + estimate = guess too low" },
        ],
        words: [
            { word: "reconstruct", hint: "To build something again", syllables: ["re", "con", "struct"] },
            { word: "reorganize", hint: "To arrange again in a new way", syllables: ["re", "or", "gan", "ize"] },
            { word: "reproduce", hint: "To make a copy or to create again", syllables: ["re", "pro", "duce"] },
            { word: "prehistoric", hint: "From the time before written history", syllables: ["pre", "his", "tor", "ic"] },
            { word: "precaution", hint: "A step taken ahead of time to prevent danger", syllables: ["pre", "cau", "tion"] },
            { word: "overwhelm", hint: "To be too much to handle", syllables: ["o", "ver", "whelm"] },
            { word: "overreact", hint: "To respond too strongly to something", syllables: ["o", "ver", "re", "act"] },
            { word: "underestimate", hint: "To think something is less than it really is", syllables: ["un", "der", "es", "ti", "mate"] },
            { word: "undergraduate", hint: "A college student who hasn't graduated yet", syllables: ["un", "der", "grad", "u", "ate"] },
            { word: "underprivileged", hint: "Not having the same advantages as others", syllables: ["un", "der", "priv", "i", "leged"] },
        ],
    },

    // ============================
    //  UNIT 5: Suffixes
    // ============================
    {
        id: "suffixes-tion-sion",
        unit: 5,
        title: "Suffixes: -tion vs -sion",
        icon: "🔚",
        color: "#e84393",
        rule: "Both -TION and -SION make a 'shun' sound. Use -TION after most consonants (especially T). Use -SION after L, N, R, or S. If the base word ends in -DE, -SE, or -D, it usually becomes -SION.",
        examples: [
            { without: "informasion", with: "information", explanation: "After T → use -TION" },
            { without: "decition", with: "decision", explanation: "From 'decide' (ends in -DE) → -SION" },
            { without: "expantion", with: "expansion", explanation: "From 'expand' (ends in -D) → -SION" },
            { without: "confution", with: "confusion", explanation: "From 'confuse' (ends in -SE) → -SION" },
        ],
        words: [
            { word: "education", hint: "The process of learning and being taught", syllables: ["ed", "u", "ca", "tion"] },
            { word: "imagination", hint: "The ability to create pictures in your mind", syllables: ["i", "mag", "i", "na", "tion"] },
            { word: "communication", hint: "Sharing information with others", syllables: ["com", "mu", "ni", "ca", "tion"] },
            { word: "competition", hint: "A contest to see who is best", syllables: ["com", "pe", "ti", "tion"] },
            { word: "explosion", hint: "A sudden violent burst", syllables: ["ex", "plo", "sion"] },
            { word: "television", hint: "A device that shows video and sound", syllables: ["tel", "e", "vi", "sion"] },
            { word: "permission", hint: "Being allowed to do something", syllables: ["per", "mis", "sion"] },
            { word: "conclusion", hint: "The end result or final decision", syllables: ["con", "clu", "sion"] },
            { word: "comprehension", hint: "Understanding something fully", syllables: ["com", "pre", "hen", "sion"] },
            { word: "profession", hint: "A job that requires special training", syllables: ["pro", "fes", "sion"] },
        ],
    },
    {
        id: "suffixes-able-ible",
        unit: 5,
        title: "Suffixes: -able vs -ible",
        icon: "✅",
        color: "#fd79a8",
        rule: "Both mean 'can be done'. Use -ABLE if the base is a complete word on its own (enjoy → enjoyable). Use -IBLE if the base is NOT a complete word (vis → visible, not visable). There are exceptions, but this works most of the time.",
        examples: [
            { without: "enjoyible", with: "enjoyable", explanation: "'Enjoy' is a complete word → -ABLE" },
            { without: "visable", with: "visible", explanation: "'Vis' is not a word → -IBLE" },
            { without: "dependible", with: "dependable", explanation: "'Depend' is a complete word → -ABLE" },
            { without: "horrble", with: "horrible", explanation: "'Horr' is not a word → -IBLE" },
        ],
        words: [
            { word: "comfortable", hint: "Feeling relaxed and at ease", syllables: ["com", "fort", "a", "ble"] },
            { word: "reasonable", hint: "Fair and sensible", syllables: ["rea", "son", "a", "ble"] },
            { word: "noticeable", hint: "Easy to see or spot", syllables: ["no", "tice", "a", "ble"] },
            { word: "fashionable", hint: "In style and trendy", syllables: ["fash", "ion", "a", "ble"] },
            { word: "responsible", hint: "In charge of something or trustworthy", syllables: ["re", "spon", "si", "ble"] },
            { word: "incredible", hint: "Hard to believe because it is so amazing", syllables: ["in", "cred", "i", "ble"] },
            { word: "accessible", hint: "Easy to reach or use", syllables: ["ac", "ces", "si", "ble"] },
            { word: "flexible", hint: "Able to bend or change easily", syllables: ["flex", "i", "ble"] },
            { word: "unpredictable", hint: "Cannot be known ahead of time", syllables: ["un", "pre", "dict", "a", "ble"] },
            { word: "compatible", hint: "Able to work well together", syllables: ["com", "pat", "i", "ble"] },
        ],
    },

    // ============================
    //  UNIT 6: Tricky Combos
    // ============================
    {
        id: "ough-patterns",
        unit: 6,
        title: "The Tricky -OUGH",
        icon: "😤",
        color: "#00b894",
        rule: "The letters OUGH can make many different sounds — this is one of the hardest parts of English. 'uff' (tough, rough), 'oh' (though, dough), 'oo' (through), 'ow' (bough, plough), 'aw' (thought, bought). You need to learn each word individually.",
        examples: [
            { without: "tuff", with: "tough", explanation: "OUGH = 'uff' sound" },
            { without: "thoh", with: "though", explanation: "OUGH = 'oh' sound" },
            { without: "throo", with: "through", explanation: "OUGH = 'oo' sound" },
            { without: "thawt", with: "thought", explanation: "OUGHT = 'aw-t' sound" },
        ],
        words: [
            { word: "enough", hint: "As much as you need", syllables: ["e", "nough"] },
            { word: "rough", hint: "Not smooth, bumpy", syllables: ["rough"] },
            { word: "tough", hint: "Strong and able to handle difficulty", syllables: ["tough"] },
            { word: "although", hint: "Even though, despite the fact", syllables: ["al", "though"] },
            { word: "thorough", hint: "Complete and careful, leaving nothing out", syllables: ["thor", "ough"] },
            { word: "throughout", hint: "In every part of something", syllables: ["through", "out"] },
            { word: "thought", hint: "An idea in your mind", syllables: ["thought"] },
            { word: "drought", hint: "A long period with no rain", syllables: ["drought"] },
            { word: "ought", hint: "Should, the right thing to do", syllables: ["ought"] },
            { word: "breakthrough", hint: "An important discovery or achievement", syllables: ["break", "through"] },
        ],
    },
    {
        id: "ph-gh-sounds",
        unit: 6,
        title: "PH = F and GH = F (or Silent)",
        icon: "📞",
        color: "#55efc4",
        rule: "PH always makes an F sound — it comes from Greek words. GH sometimes makes an F sound (laugh, cough) and is sometimes silent (night, daughter). At the start of a word, GH is always hard G (ghost, ghastly).",
        examples: [
            { without: "fonetic", with: "phonetic", explanation: "PH = F sound (from Greek)" },
            { without: "laf", with: "laugh", explanation: "GH = F sound at end of word" },
            { without: "nite", with: "night", explanation: "GH is silent after I" },
            { without: "gost", with: "ghost", explanation: "GH = hard G at start of word" },
        ],
        words: [
            { word: "photograph", hint: "A picture taken with a camera", syllables: ["pho", "to", "graph"] },
            { word: "philosophy", hint: "The study of big questions about life and meaning", syllables: ["phi", "los", "o", "phy"] },
            { word: "paragraph", hint: "A section of writing with related sentences", syllables: ["par", "a", "graph"] },
            { word: "telephone", hint: "A device for talking to someone far away", syllables: ["tel", "e", "phone"] },
            { word: "laughter", hint: "The sound of laughing", syllables: ["laugh", "ter"] },
            { word: "daughter", hint: "A female child", syllables: ["daugh", "ter"] },
            { word: "straightforward", hint: "Simple and easy to understand", syllables: ["straight", "for", "ward"] },
            { word: "neighborhood", hint: "The area around where you live", syllables: ["neigh", "bor", "hood"] },
            { word: "physical", hint: "Related to the body", syllables: ["phys", "i", "cal"] },
            { word: "atmosphere", hint: "The layer of air around Earth", syllables: ["at", "mos", "phere"] },
        ],
    },

    // ============================
    //  UNIT 7: Commonly Confused
    // ============================
    {
        id: "confused-words",
        unit: 7,
        title: "Commonly Confused Words",
        icon: "🤔",
        color: "#0984e3",
        rule: "Some words sound the same (or nearly the same) but are spelled differently and mean different things. These are called homophones. You need to know which spelling matches which meaning.",
        examples: [
            { without: "there going", with: "they're going", explanation: "THEY'RE = they are" },
            { without: "over their", with: "over there", explanation: "THERE = a place" },
            { without: "its raining", with: "it's raining", explanation: "IT'S = it is" },
            { without: "the affect", with: "the effect", explanation: "EFFECT = noun (the result)" },
        ],
        words: [
            { word: "definitely", hint: "Without any doubt (not 'definately')", syllables: ["def", "i", "nite", "ly"] },
            { word: "separate", hint: "To divide apart (not 'seperate' — think 'a rat' in the middle)", syllables: ["sep", "a", "rate"] },
            { word: "necessary", hint: "Needed (one C, two S's — one Collar, two Socks)", syllables: ["nec", "es", "sar", "y"] },
            { word: "occasion", hint: "A special event (two C's, one S)", syllables: ["oc", "ca", "sion"] },
            { word: "independent", hint: "Not relying on others (ends in -ent, not -ant)", syllables: ["in", "de", "pen", "dent"] },
            { word: "existence", hint: "The state of being real (ends in -ence, not -ance)", syllables: ["ex", "is", "tence"] },
            { word: "privilege", hint: "A special right or advantage (no D — not 'priviledge')", syllables: ["priv", "i", "lege"] },
            { word: "schedule", hint: "A plan for when things happen", syllables: ["sched", "ule"] },
            { word: "maintenance", hint: "Keeping something in good condition (main + ten + ance)", syllables: ["main", "ten", "ance"] },
            { word: "occurrence", hint: "Something that happens (double C, double R)", syllables: ["oc", "cur", "rence"] },
        ],
    },

    // ============================
    //  UNIT 8: Greek & Latin Roots
    // ============================
    {
        id: "greek-roots",
        unit: 8,
        title: "Greek Roots: bio, graph, phon, scope",
        icon: "🏛️",
        color: "#d63031",
        rule: "Many English words come from Greek roots. BIO = life. GRAPH/GRAM = write/draw. PHON = sound. SCOPE = see/watch. AUTO = self. TELE = far. If you learn these roots, you can decode words you've never seen before.",
        examples: [
            { without: "life study", with: "biology", explanation: "BIO (life) + LOGY (study of)" },
            { without: "far sound", with: "telephone", explanation: "TELE (far) + PHONE (sound)" },
            { without: "self life story", with: "autobiography", explanation: "AUTO (self) + BIO (life) + GRAPH (write)" },
            { without: "small see", with: "microscope", explanation: "MICRO (small) + SCOPE (see)" },
        ],
        words: [
            { word: "biography", hint: "A written story of someone's life", syllables: ["bi", "og", "ra", "phy"] },
            { word: "geography", hint: "The study of Earth's places and features", syllables: ["ge", "og", "ra", "phy"] },
            { word: "autograph", hint: "A person's own signature", syllables: ["au", "to", "graph"] },
            { word: "microphone", hint: "A device that picks up sound", syllables: ["mi", "cro", "phone"] },
            { word: "telescope", hint: "A device for seeing things far away", syllables: ["tel", "e", "scope"] },
            { word: "microscope", hint: "A device for seeing very small things", syllables: ["mi", "cro", "scope"] },
            { word: "autobiography", hint: "A story of your own life written by you", syllables: ["au", "to", "bi", "og", "ra", "phy"] },
            { word: "photography", hint: "The art of taking pictures", syllables: ["pho", "tog", "ra", "phy"] },
            { word: "symphony", hint: "A large musical composition for an orchestra", syllables: ["sym", "pho", "ny"] },
            { word: "antibiotics", hint: "Medicine that kills bacteria", syllables: ["an", "ti", "bi", "ot", "ics"] },
        ],
    },
    {
        id: "latin-roots",
        unit: 8,
        title: "Latin Roots: rupt, struct, port, ject",
        icon: "📚",
        color: "#e55039",
        rule: "Latin roots are everywhere in English. RUPT = break. STRUCT = build. PORT = carry. JECT = throw. DICT = say/speak. DUCT = lead. Knowing these helps you figure out unfamiliar words.",
        examples: [
            { without: "break apart", with: "interrupt", explanation: "INTER (between) + RUPT (break)" },
            { without: "build together", with: "construct", explanation: "CON (together) + STRUCT (build)" },
            { without: "carry out", with: "export", explanation: "EX (out) + PORT (carry)" },
            { without: "throw back", with: "reject", explanation: "RE (back) + JECT (throw)" },
        ],
        words: [
            { word: "interrupt", hint: "To break into a conversation", syllables: ["in", "ter", "rupt"] },
            { word: "corruption", hint: "Dishonest behavior that breaks trust", syllables: ["cor", "rup", "tion"] },
            { word: "destruction", hint: "The act of breaking something completely", syllables: ["de", "struc", "tion"] },
            { word: "infrastructure", hint: "The basic systems a society is built on", syllables: ["in", "fra", "struc", "ture"] },
            { word: "transportation", hint: "Carrying people or goods from place to place", syllables: ["trans", "por", "ta", "tion"] },
            { word: "opportunity", hint: "A chance (carries you toward something)", syllables: ["op", "por", "tu", "ni", "ty"] },
            { word: "injection", hint: "Throwing medicine into the body with a needle", syllables: ["in", "jec", "tion"] },
            { word: "projection", hint: "Throwing an image forward onto a screen", syllables: ["pro", "jec", "tion"] },
            { word: "dictionary", hint: "A book that speaks the meaning of words", syllables: ["dic", "tion", "ar", "y"] },
            { word: "introduction", hint: "Leading someone into a new topic or person", syllables: ["in", "tro", "duc", "tion"] },
        ],
    },

    // ============================
    //  UNIT 9: Plurals & Word Endings
    // ============================
    {
        id: "plural-rules",
        unit: 9,
        title: "Tricky Plurals",
        icon: "📦",
        color: "#636e72",
        rule: "Most words add -S. Words ending in S, SH, CH, X, Z add -ES. Words ending in consonant + Y change Y to I and add -ES (city → cities). Words ending in F or FE often change to -VES (knife → knives). Some are irregular (child → children).",
        examples: [
            { without: "boxs", with: "boxes", explanation: "Ends in X → add -ES" },
            { without: "citys", with: "cities", explanation: "Consonant + Y → change to -IES" },
            { without: "knifes", with: "knives", explanation: "FE → VES" },
            { without: "childs", with: "children", explanation: "Irregular — just memorize it" },
        ],
        words: [
            { word: "categories", hint: "Groups or classes of things (category → categories)", syllables: ["cat", "e", "gor", "ies"] },
            { word: "opportunities", hint: "Chances to do something (opportunity → opportunities)", syllables: ["op", "por", "tu", "ni", "ties"] },
            { word: "responsibilities", hint: "Duties you are in charge of", syllables: ["re", "spon", "si", "bil", "i", "ties"] },
            { word: "strategies", hint: "Plans for achieving goals", syllables: ["strat", "e", "gies"] },
            { word: "boundaries", hint: "Lines that mark the edge of an area", syllables: ["bound", "a", "ries"] },
            { word: "themselves", hint: "Used when they do something to their own group", syllables: ["them", "selves"] },
            { word: "analyses", hint: "Detailed examinations of something (analysis → analyses)", syllables: ["a", "nal", "y", "ses"] },
            { word: "phenomena", hint: "Observable events (phenomenon → phenomena)", syllables: ["phe", "nom", "e", "na"] },
            { word: "criteria", hint: "Standards for judging (criterion → criteria)", syllables: ["cri", "te", "ri", "a"] },
            { word: "consequences", hint: "Results of actions", syllables: ["con", "se", "quen", "ces"] },
        ],
    },
    // ============================
    //  UNIT 10: Vowel Patterns
    // ============================
    {
        id: "vowel-teams",
        unit: 10,
        title: "Vowel Teams (ai, ea, oa, ee)",
        icon: "👥",
        color: "#74b9ff",
        rule: "When two vowels appear side by side, they often work as a team to make one sound. Usually the first vowel says its name (long sound) and the second is silent. Remember the rhyme: 'When two vowels go walking, the first one does the talking.'",
        examples: [
            { without: "rane", with: "rain", explanation: "AI makes the long A sound" },
            { without: "bote", with: "boat", explanation: "OA makes the long O sound" },
            { without: "meen", with: "mean", explanation: "EA makes the long E sound" },
            { without: "slep", with: "sleep", explanation: "EE makes the long E sound" },
        ],
        words: [
            { word: "explain", hint: "To make something clear to someone", syllables: ["ex", "plain"] },
            { word: "approach", hint: "To come closer to something", syllables: ["ap", "proach"] },
            { word: "proceed", hint: "To continue moving forward", syllables: ["pro", "ceed"] },
            { word: "maintain", hint: "To keep something in good condition", syllables: ["main", "tain"] },
            { word: "release", hint: "To let go of something", syllables: ["re", "lease"] },
            { word: "contain", hint: "To hold something inside", syllables: ["con", "tain"] },
            { word: "defeat", hint: "To win against an opponent", syllables: ["de", "feat"] },
            { word: "retreat", hint: "To move back or withdraw", syllables: ["re", "treat"] },
            { word: "succeed", hint: "To achieve what you tried to do", syllables: ["suc", "ceed"] },
            { word: "increase", hint: "To become larger or greater", syllables: ["in", "crease"] },
        ],
    },
    {
        id: "magic-e-patterns",
        unit: 10,
        title: "Magic E in Longer Words",
        icon: "✨",
        color: "#a29bfe",
        rule: "The Magic E rule doesn't just work in small words like 'hope' — it shows up in longer words too. Look for the pattern: consonant + vowel + consonant + E at the end of a syllable. The E stays silent but makes the vowel say its name.",
        examples: [
            { without: "compeet", with: "compete", explanation: "The E makes the second E say its name" },
            { without: "surviv", with: "survive", explanation: "The E makes the I say its name" },
            { without: "invit", with: "invite", explanation: "The E makes the I say its name" },
            { without: "explod", with: "explode", explanation: "The E makes the O say its name" },
        ],
        words: [
            { word: "escape", hint: "To get away from danger", syllables: ["es", "cape"] },
            { word: "compete", hint: "To try to win against others", syllables: ["com", "pete"] },
            { word: "explore", hint: "To travel and discover new things", syllables: ["ex", "plore"] },
            { word: "extreme", hint: "Very great or intense", syllables: ["ex", "treme"] },
            { word: "decline", hint: "To go down or politely say no", syllables: ["de", "cline"] },
            { word: "compose", hint: "To create music or writing", syllables: ["com", "pose"] },
            { word: "combine", hint: "To join things together into one", syllables: ["com", "bine"] },
            { word: "migrate", hint: "To move from one place to another", syllables: ["mi", "grate"] },
            { word: "immune", hint: "Protected from a disease", syllables: ["im", "mune"] },
            { word: "dispute", hint: "An argument or disagreement", syllables: ["dis", "pute"] },
        ],
    },

    // ============================
    //  UNIT 11: Soft Sounds
    // ============================
    {
        id: "soft-c-g",
        unit: 11,
        title: "Soft C and Soft G",
        icon: "🔉",
        color: "#ffeaa7",
        rule: "The letters C and G each have two sounds. C says 'S' when followed by E, I, or Y (like 'city' and 'center'). G says 'J' when followed by E, I, or Y (like 'giant' and 'gentle'). Before A, O, U, or consonants, C says 'K' and G says hard 'G'.",
        examples: [
            { without: "sircle", with: "circle", explanation: "C before I makes the S sound" },
            { without: "jiant", with: "giant", explanation: "G before I makes the J sound" },
            { without: "senter", with: "center", explanation: "C before E makes the S sound" },
            { without: "jentle", with: "gentle", explanation: "G before E makes the J sound" },
        ],
        words: [
            { word: "citizen", hint: "A person who belongs to a country", syllables: ["cit", "i", "zen"] },
            { word: "imagine", hint: "To picture something in your mind", syllables: ["i", "mag", "ine"] },
            { word: "general", hint: "Overall, or a high military rank", syllables: ["gen", "er", "al"] },
            { word: "century", hint: "A period of one hundred years", syllables: ["cen", "tu", "ry"] },
            { word: "generous", hint: "Willing to give and share freely", syllables: ["gen", "er", "ous"] },
            { word: "ceremony", hint: "A formal event or celebration", syllables: ["cer", "e", "mo", "ny"] },
            { word: "emergency", hint: "A sudden dangerous situation", syllables: ["e", "mer", "gen", "cy"] },
            { word: "principal", hint: "The head of a school", syllables: ["prin", "ci", "pal"] },
            { word: "original", hint: "The first, not a copy", syllables: ["o", "rig", "i", "nal"] },
            { word: "innocent", hint: "Not guilty of a crime", syllables: ["in", "no", "cent"] },
        ],
    },

    // ============================
    //  UNIT 12: R-Controlled Vowels
    // ============================
    {
        id: "r-controlled",
        unit: 12,
        title: "Bossy R Vowels (ar, er, ir, or, ur)",
        icon: "🏴‍☠️",
        color: "#fab1a0",
        rule: "When the letter R comes after a vowel, it changes the vowel's sound completely — that's why we call it 'Bossy R'. AR sounds like 'car'. ER, IR, and UR all make the same 'er' sound (her, bird, fur). OR sounds like 'for'. The tricky part is knowing which spelling to use for the 'er' sound.",
        examples: [
            { without: "gaden", with: "garden", explanation: "AR makes the 'ar' sound" },
            { without: "nervus", with: "nervous", explanation: "ER makes the 'er' sound" },
            { without: "thersty", with: "thirsty", explanation: "IR also makes the 'er' sound" },
            { without: "perpus", with: "purpose", explanation: "UR also makes the 'er' sound" },
        ],
        words: [
            { word: "departure", hint: "The act of leaving a place", syllables: ["de", "par", "ture"] },
            { word: "determine", hint: "To find out or decide firmly", syllables: ["de", "ter", "mine"] },
            { word: "circular", hint: "Shaped like a circle, round", syllables: ["cir", "cu", "lar"] },
            { word: "therefore", hint: "For that reason, so", syllables: ["there", "fore"] },
            { word: "surprise", hint: "Something you didn't expect", syllables: ["sur", "prise"] },
            { word: "perform", hint: "To carry out an action or show", syllables: ["per", "form"] },
            { word: "murmur", hint: "To speak very softly", syllables: ["mur", "mur"] },
            { word: "particular", hint: "Specific, one certain thing", syllables: ["par", "tic", "u", "lar"] },
            { word: "furniture", hint: "Tables, chairs, desks, and beds", syllables: ["fur", "ni", "ture"] },
            { word: "fortunate", hint: "Lucky, having good fortune", syllables: ["for", "tu", "nate"] },
        ],
    },

    // ============================
    //  UNIT 13: Word Families
    // ============================
    {
        id: "ight-family",
        unit: 13,
        title: "The -ight Family & -tion Pattern",
        icon: "👨‍👩‍👧‍👦",
        color: "#55efc4",
        rule: "English has word families — groups of words that share a spelling pattern. The -IGHT family makes a 'ite' sound (the GH is silent). The -TION pattern always makes a 'shun' sound. Learning these families helps you spell many words at once.",
        examples: [
            { without: "nite", with: "night", explanation: "-IGHT says 'ite' — GH is silent" },
            { without: "fite", with: "fight", explanation: "-IGHT pattern, same as night" },
            { without: "nashun", with: "nation", explanation: "-TION always says 'shun'" },
            { without: "stashun", with: "station", explanation: "-TION pattern, same sound" },
        ],
        words: [
            { word: "midnight", hint: "12 o'clock at night", syllables: ["mid", "night"] },
            { word: "spotlight", hint: "A bright beam of light on a stage", syllables: ["spot", "light"] },
            { word: "frightened", hint: "Feeling scared or afraid", syllables: ["fright", "ened"] },
            { word: "delightful", hint: "Very pleasing and enjoyable", syllables: ["de", "light", "ful"] },
            { word: "straighten", hint: "To make something not crooked", syllables: ["straight", "en"] },
            { word: "situation", hint: "The circumstances you're in", syllables: ["sit", "u", "a", "tion"] },
            { word: "operation", hint: "A medical procedure or a planned action", syllables: ["op", "er", "a", "tion"] },
            { word: "generation", hint: "A group of people born around the same time", syllables: ["gen", "er", "a", "tion"] },
            { word: "celebration", hint: "A party or special event", syllables: ["cel", "e", "bra", "tion"] },
            { word: "information", hint: "Facts and details about something", syllables: ["in", "for", "ma", "tion"] },
        ],
    },
    {
        id: "ous-ful-less",
        unit: 13,
        title: "Endings: -ous, -ful, -less, -ment, -ness",
        icon: "🔗",
        color: "#81ecec",
        rule: "These common endings help build new words. -OUS means 'full of' (danger → dangerous). -FUL means 'full of' (hope → hopeful). -LESS means 'without' (hope → hopeless). -MENT turns a verb into a noun (enjoy → enjoyment). -NESS turns an adjective into a noun (dark → darkness).",
        examples: [
            { without: "dangeros", with: "dangerous", explanation: "-OUS means 'full of danger'" },
            { without: "hopful", with: "hopeful", explanation: "-FUL means 'full of hope'" },
            { without: "carelss", with: "careless", explanation: "-LESS means 'without care'" },
            { without: "enjoiment", with: "enjoyment", explanation: "-MENT turns a verb into a noun" },
        ],
        words: [
            { word: "courageous", hint: "Full of courage, very brave", syllables: ["cour", "a", "geous"] },
            { word: "mysterious", hint: "Full of mystery, hard to explain", syllables: ["mys", "te", "ri", "ous"] },
            { word: "ridiculous", hint: "So silly it deserves to be laughed at", syllables: ["ri", "dic", "u", "lous"] },
            { word: "meaningful", hint: "Full of meaning and purpose", syllables: ["mean", "ing", "ful"] },
            { word: "thoughtful", hint: "Showing care for others' feelings", syllables: ["thought", "ful"] },
            { word: "reckless", hint: "Without thought for danger", syllables: ["reck", "less"] },
            { word: "regardless", hint: "Without regard, no matter what", syllables: ["re", "gard", "less"] },
            { word: "achievement", hint: "Something accomplished through effort", syllables: ["a", "chieve", "ment"] },
            { word: "government", hint: "The system that runs a country", syllables: ["gov", "ern", "ment"] },
            { word: "awareness", hint: "The state of knowing about something", syllables: ["a", "ware", "ness"] },
        ],
    },
];

// Build a quick lookup: unit number → lessons in that unit
const LESSON_UNITS = {};
LESSONS.forEach((lesson) => {
    if (!LESSON_UNITS[lesson.unit]) LESSON_UNITS[lesson.unit] = [];
    LESSON_UNITS[lesson.unit].push(lesson);
});

const UNIT_NAMES = {
    1: "Silent Letters",
    2: "Double Letters",
    3: "I Before E",
    4: "Prefixes",
    5: "Suffixes",
    6: "Tricky Combos",
    7: "Commonly Confused",
    8: "Greek & Latin Roots",
    9: "Plurals & Endings",
    10: "Vowel Patterns",
    11: "Soft Sounds",
    12: "R-Controlled Vowels",
    13: "Word Families & Endings",
};
