// Word lists organized by difficulty level — age-appropriate for a 13-year-old
// Each word has: word, hint, syllables (for visual breakdown), sentence (contextual usage)
// 5 levels, 30 words each — difficulty increases with each level

const WORD_LISTS = {
    "Level 1": {
        icon: "🟢",
        color: "#00cec9",
        words: [
            { word: "brain", hint: "The organ that controls your body", syllables: ["brain"], sentence: "Your brain processes millions of signals every single second." },
            { word: "heart", hint: "It pumps blood through your body", syllables: ["heart"], sentence: "Her heart was beating fast after she finished the race." },
            { word: "write", hint: "To put words on paper", syllables: ["write"], sentence: "I need to write a short essay for English class tomorrow." },
            { word: "light", hint: "The opposite of dark", syllables: ["light"], sentence: "The light from the sunset turned the sky bright orange." },
            { word: "dream", hint: "Images you see while sleeping", syllables: ["dream"], sentence: "Last night I had a dream about flying over the mountains." },
            { word: "climb", hint: "To go upward, like a mountain", syllables: ["climb"], sentence: "We plan to climb the tallest hill in the state park." },
            { word: "watch", hint: "To look at something carefully", syllables: ["watch"], sentence: "I like to watch the stars on clear summer nights." },
            { word: "earth", hint: "The planet we live on", syllables: ["earth"], sentence: "The earth travels around the sun once every year." },
            { word: "guard", hint: "To protect or keep safe", syllables: ["guard"], sentence: "The dog would guard the house whenever we left for school." },
            { word: "doubt", hint: "To be unsure about something", syllables: ["doubt"], sentence: "I doubt it will rain today since the sky looks clear." },
            { word: "whole", hint: "All of it, complete", syllables: ["whole"], sentence: "She ate the whole pizza before anyone else got a slice." },
            { word: "guide", hint: "Someone who shows the way", syllables: ["guide"], sentence: "The tour guide showed us the best spots in the city." },
            { word: "scene", hint: "A part of a movie or play", syllables: ["scene"], sentence: "The opening scene of that movie had everyone on the edge of their seats." },
            { word: "noise", hint: "A loud or unwanted sound", syllables: ["noise"], sentence: "The loud noise from the construction woke me up early." },
            { word: "built", hint: "Past tense of build", syllables: ["built"], sentence: "They built a new skate park right next to our school." },
            { word: "truth", hint: "The opposite of a lie", syllables: ["truth"], sentence: "It is always better to tell the truth than to lie." },
            { word: "world", hint: "The earth and all its people", syllables: ["world"], sentence: "There are almost eight billion people living in the world today." },
            { word: "young", hint: "Not old", syllables: ["young"], sentence: "She was young but already knew what career she wanted." },
            { word: "field", hint: "An open area of land", syllables: ["field"], sentence: "The soccer team practiced every afternoon on the open field." },
            { word: "piece", hint: "A part of something", syllables: ["piece"], sentence: "Can I have one more piece of that chocolate cake please?" },
            { word: "touch", hint: "To feel with your hands", syllables: ["touch"], sentence: "Be careful not to touch the screen with dirty fingers." },
            { word: "group", hint: "A collection of people or things", syllables: ["group"], sentence: "Our group finished the science project a day early." },
            { word: "phone", hint: "A device for calling people", syllables: ["phone"], sentence: "I forgot my phone at home and felt lost all day." },
            { word: "knife", hint: "A sharp tool for cutting", syllables: ["knife"], sentence: "He used a sharp knife to cut the rope in half." },
            { word: "ocean", hint: "A very large body of salt water", syllables: ["o", "cean"], sentence: "The ocean stretched out as far as we could see." },
            { word: "quiet", hint: "Making little or no noise", syllables: ["qui", "et"], sentence: "The library was so quiet you could hear a pin drop." },
            { word: "above", hint: "Higher than something else", syllables: ["a", "bove"], sentence: "The hawk circled slowly above the trees looking for food." },
            { word: "sugar", hint: "A sweet substance used in food", syllables: ["sug", "ar"], sentence: "Too much sugar in your diet can be bad for your teeth." },
            { word: "basic", hint: "Simple, the foundation of something", syllables: ["ba", "sic"], sentence: "Learning the basic rules of coding is easier than you think." },
            { word: "human", hint: "A person, a member of our species", syllables: ["hu", "man"], sentence: "Every human being deserves to be treated with respect and kindness." },
        ],
    },
    "Level 2": {
        icon: "🔵",
        color: "#0984e3",
        words: [
            { word: "bridge", hint: "A structure built over water or a valley", syllables: ["bridge"], sentence: "We walked across the old stone bridge to reach the other side." },
            { word: "island", hint: "Land surrounded by water on all sides", syllables: ["is", "land"], sentence: "The tiny island was only reachable by boat or helicopter." },
            { word: "castle", hint: "A large old building with towers and walls", syllables: ["cas", "tle"], sentence: "The ancient castle on the hilltop had been there for centuries." },
            { word: "forest", hint: "A large area covered with trees", syllables: ["for", "est"], sentence: "The forest was so thick that barely any sunlight reached the ground." },
            { word: "nature", hint: "The natural world around us", syllables: ["na", "ture"], sentence: "Spending time in nature can help you feel calm and relaxed." },
            { word: "frozen", hint: "Turned to ice, very cold", syllables: ["fro", "zen"], sentence: "The lake was completely frozen so we could walk on it." },
            { word: "design", hint: "To plan and create something new", syllables: ["de", "sign"], sentence: "She wants to design video games when she grows up." },
            { word: "battle", hint: "A fight between armies in a war", syllables: ["bat", "tle"], sentence: "The final battle in the book was the most exciting chapter." },
            { word: "signal", hint: "A sign that gives information", syllables: ["sig", "nal"], sentence: "My phone lost its signal when we drove through the tunnel." },
            { word: "travel", hint: "To go from place to place", syllables: ["trav", "el"], sentence: "I hope to travel to Japan and see the cherry blossoms someday." },
            { word: "silver", hint: "A shiny grey precious metal", syllables: ["sil", "ver"], sentence: "She wore a silver necklace that her grandmother had given her." },
            { word: "breath", hint: "Air going in and out of your lungs", syllables: ["breath"], sentence: "He took a deep breath before stepping onto the stage." },
            { word: "season", hint: "Spring, summer, fall, or winter", syllables: ["sea", "son"], sentence: "Fall is my favorite season because of the colorful leaves." },
            { word: "double", hint: "Twice as much", syllables: ["dou", "ble"], sentence: "He asked for a double scoop of ice cream on his cone." },
            { word: "flight", hint: "Traveling through the air", syllables: ["flight"], sentence: "Our flight to New York was delayed because of the storm." },
            { word: "knight", hint: "An armored medieval warrior", syllables: ["knight"], sentence: "The brave knight rode through the kingdom on a white horse." },
            { word: "tongue", hint: "The muscle inside your mouth", syllables: ["tongue"], sentence: "She burned her tongue by sipping the hot soup too quickly." },
            { word: "rhythm", hint: "A regular pattern of beats in music", syllables: ["rhy", "thm"], sentence: "The drummer kept a steady rhythm throughout the entire song." },
            { word: "column", hint: "A tall pillar or a vertical line", syllables: ["col", "umn"], sentence: "A tall marble column stood at the entrance of the museum." },
            { word: "league", hint: "A group of sports teams that compete", syllables: ["league"], sentence: "He joined a basketball league that plays games every weekend." },
            { word: "bought", hint: "Past tense of buy", syllables: ["bought"], sentence: "She bought a new backpack for the first day of school." },
            { word: "caught", hint: "Past tense of catch", syllables: ["caught"], sentence: "He caught the ball right before it went over the fence." },
            { word: "muscle", hint: "Body tissue that creates movement", syllables: ["mus", "cle"], sentence: "You need to stretch each muscle before doing intense exercise." },
            { word: "science", hint: "The study of the natural world", syllables: ["sci", "ence"], sentence: "Our science class did a cool experiment with dry ice today." },
            { word: "trouble", hint: "A problem or difficulty", syllables: ["trou", "ble"], sentence: "Staying up too late on school nights can lead to trouble." },
            { word: "stomach", hint: "The organ that digests your food", syllables: ["stom", "ach"], sentence: "My stomach started growling right in the middle of the test." },
            { word: "weather", hint: "Rain, sun, wind, or snow outside", syllables: ["weath", "er"], sentence: "Check the weather forecast before you decide what to wear today." },
            { word: "million", hint: "The number 1,000,000", syllables: ["mil", "lion"], sentence: "The popular video got over a million views in one day." },
            { word: "ancient", hint: "From a very long time ago", syllables: ["an", "cient"], sentence: "We learned about ancient Egypt and the building of the pyramids." },
            { word: "vehicle", hint: "A car, bus, truck, or other transport", syllables: ["ve", "hi", "cle"], sentence: "Every vehicle on the road must stop at a red light." },
        ],
    },
    "Level 3": {
        icon: "🟡",
        color: "#feca57",
        words: [
            { word: "thought", hint: "An idea in your mind", syllables: ["thought"], sentence: "I thought the math test was going to be much harder." },
            { word: "through", hint: "From one side to the other", syllables: ["through"], sentence: "We hiked through the valley and reached the campsite before dark." },
            { word: "foreign", hint: "From another country", syllables: ["for", "eign"], sentence: "Learning a foreign language opens up a whole new world." },
            { word: "captain", hint: "The leader of a team or ship", syllables: ["cap", "tain"], sentence: "The captain of our soccer team gave an inspiring speech before the game." },
            { word: "certain", hint: "Sure about something, without doubt", syllables: ["cer", "tain"], sentence: "I am certain that I locked the front door before leaving." },
            { word: "special", hint: "Different from the usual, unique", syllables: ["spe", "cial"], sentence: "Mom made a special dinner to celebrate my birthday this year." },
            { word: "library", hint: "A building full of books to borrow", syllables: ["li", "brar", "y"], sentence: "I found an amazing graphic novel at the library last week." },
            { word: "mystery", hint: "Something unknown or puzzling", syllables: ["mys", "ter", "y"], sentence: "The disappearance of the missing homework remained a total mystery." },
            { word: "history", hint: "The study of the past", syllables: ["his", "tor", "y"], sentence: "My history teacher makes even boring topics sound really interesting." },
            { word: "picture", hint: "A photo or drawing", syllables: ["pic", "ture"], sentence: "She drew a picture of her dog that looked incredibly realistic." },
            { word: "machine", hint: "A device that does work", syllables: ["ma", "chine"], sentence: "The machine in the gym tracks how many calories you burn." },
            { word: "surface", hint: "The outside layer of something", syllables: ["sur", "face"], sentence: "The surface of the lake was perfectly calm and still that morning." },
            { word: "courage", hint: "Being brave even when scared", syllables: ["cour", "age"], sentence: "It takes real courage to stand up for what you believe in." },
            { word: "balance", hint: "Keeping steady and even", syllables: ["bal", "ance"], sentence: "Good balance is important when you are learning to skateboard." },
            { word: "ceiling", hint: "The top inside of a room", syllables: ["ceil", "ing"], sentence: "The ceiling of the gym was high enough for indoor rock climbing." },
            { word: "receive", hint: "To get something given to you", syllables: ["re", "ceive"], sentence: "You should receive your test results by the end of the week." },
            { word: "believe", hint: "To think something is true", syllables: ["be", "lieve"], sentence: "I believe that hard work always pays off in the end." },
            { word: "achieve", hint: "To reach a goal through effort", syllables: ["a", "chieve"], sentence: "With daily practice you can achieve almost any goal you set." },
            { word: "separate", hint: "To divide into parts (think: a rat in the middle)", syllables: ["sep", "a", "rate"], sentence: "Please separate the recyclables from the regular trash before going out." },
            { word: "surprise", hint: "Something unexpected", syllables: ["sur", "prise"], sentence: "The surprise party for our teacher went exactly as we planned." },
            { word: "strength", hint: "The quality of being strong", syllables: ["strength"], sentence: "Building inner strength helps you handle difficult situations with confidence." },
            { word: "material", hint: "What something is made of", syllables: ["ma", "te", "ri", "al"], sentence: "The material of this jacket keeps you warm even in freezing weather." },
            { word: "practice", hint: "To do something again and again to improve", syllables: ["prac", "tice"], sentence: "If you practice the piano every day you will improve quickly." },
            { word: "pressure", hint: "Force pushing against something", syllables: ["pres", "sure"], sentence: "Try not to put too much pressure on yourself before exams." },
            { word: "possible", hint: "Able to happen or be done", syllables: ["pos", "si", "ble"], sentence: "Anything is possible when you stay focused and keep trying." },
            { word: "physical", hint: "Related to the body, not the mind", syllables: ["phys", "i", "cal"], sentence: "Regular physical activity helps keep both your body and mind healthy." },
            { word: "response", hint: "An answer or reply", syllables: ["re", "sponse"], sentence: "Her quick response to the question impressed the entire class." },
            { word: "position", hint: "A place, location, or rank", syllables: ["po", "si", "tion"], sentence: "He played the goalie position for the first time this season." },
            { word: "calendar", hint: "Shows days and months of the year", syllables: ["cal", "en", "dar"], sentence: "I marked all my exam dates on the calendar so I would not forget." },
            { word: "opposite", hint: "Completely different from something", syllables: ["op", "po", "site"], sentence: "Hot and cold are opposite words that mean very different things." },
        ],
    },
    "Level 4": {
        icon: "🟠",
        color: "#e17055",
        words: [
            { word: "knowledge", hint: "What you know and understand", syllables: ["knowl", "edge"], sentence: "Reading books is one of the best ways to gain new knowledge." },
            { word: "daughter", hint: "A female child of a parent", syllables: ["daugh", "ter"], sentence: "Their daughter won first place at the school science fair this year." },
            { word: "beautiful", hint: "Very pleasing to look at", syllables: ["beau", "ti", "ful"], sentence: "The sunset over the ocean was the most beautiful thing I ever saw." },
            { word: "dangerous", hint: "Could cause harm or injury", syllables: ["dan", "ger", "ous"], sentence: "Swimming in the river during a flood is extremely dangerous." },
            { word: "invisible", hint: "Cannot be seen", syllables: ["in", "vis", "i", "ble"], sentence: "Some gases are invisible but you can still smell them in the air." },
            { word: "lightning", hint: "A flash of electricity in a storm", syllables: ["light", "ning"], sentence: "A bright bolt of lightning lit up the entire night sky." },
            { word: "necessary", hint: "Needed, you can't do without it", syllables: ["nec", "es", "sar", "y"], sentence: "Drinking enough water every day is necessary for staying healthy." },
            { word: "orchestra", hint: "A large group of musicians playing together", syllables: ["or", "ches", "tra"], sentence: "The school orchestra performed a stunning concert for the whole community." },
            { word: "passenger", hint: "Someone riding in a vehicle", syllables: ["pas", "sen", "ger"], sentence: "Every passenger on the bus must wear a seatbelt at all times." },
            { word: "continent", hint: "One of Earth's large land masses", syllables: ["con", "ti", "nent"], sentence: "Africa is the second largest continent in the entire world." },
            { word: "different", hint: "Not the same as something else", syllables: ["dif", "fer", "ent"], sentence: "Everyone learns in a different way and that is perfectly okay." },
            { word: "beginning", hint: "The start of something", syllables: ["be", "gin", "ning"], sentence: "The beginning of the movie was slow but it got really exciting." },
            { word: "attention", hint: "Focus on something carefully", syllables: ["at", "ten", "tion"], sentence: "Pay close attention to the instructions before starting the experiment." },
            { word: "challenge", hint: "Something that is hard to do", syllables: ["chal", "lenge"], sentence: "Every new challenge you face is a chance to learn and grow." },
            { word: "technique", hint: "A specific way of doing something", syllables: ["tech", "nique"], sentence: "The artist used a shading technique that made the drawing look realistic." },
            { word: "recognize", hint: "To identify something you've seen before", syllables: ["rec", "og", "nize"], sentence: "I could barely recognize my friend after his completely new haircut." },
            { word: "equipment", hint: "Tools and gear needed for a task", syllables: ["e", "quip", "ment"], sentence: "Make sure you have all the right equipment before the camping trip." },
            { word: "guarantee", hint: "A promise that something will work", syllables: ["guar", "an", "tee"], sentence: "The store offers a money-back guarantee if the product breaks." },
            { word: "Wednesday", hint: "The middle day of the work week", syllables: ["Wed", "nes", "day"], sentence: "We have a math quiz every Wednesday so I study on Tuesday night." },
            { word: "education", hint: "The process of learning and being taught", syllables: ["ed", "u", "ca", "tion"], sentence: "A good education helps you build a better future for yourself." },
            { word: "atmosphere", hint: "The layer of air around the Earth", syllables: ["at", "mos", "phere"], sentence: "The atmosphere protects us from harmful radiation coming from the sun." },
            { word: "experience", hint: "Something that happens to you in life", syllables: ["ex", "pe", "ri", "ence"], sentence: "Traveling to a new country is an unforgettable experience for anyone." },
            { word: "adventure", hint: "An exciting or unusual experience", syllables: ["ad", "ven", "ture"], sentence: "Our camping trip turned into a real adventure when we got lost." },
            { word: "determine", hint: "To figure something out or decide", syllables: ["de", "ter", "mine"], sentence: "Scientists ran several tests to determine the cause of the problem." },
            { word: "interrupt", hint: "To stop someone while they're speaking", syllables: ["in", "ter", "rupt"], sentence: "Please do not interrupt when someone else is speaking in class." },
            { word: "jealousy", hint: "Wanting what someone else has", syllables: ["jeal", "ous", "y"], sentence: "Jealousy can ruin friendships if you let it take control." },
            { word: "imaginary", hint: "Existing only in the mind, not real", syllables: ["i", "mag", "i", "nar", "y"], sentence: "The book takes place in an imaginary world filled with dragons." },
            { word: "disappear", hint: "To vanish from sight", syllables: ["dis", "ap", "pear"], sentence: "The magician made the coin disappear right before our eyes." },
            { word: "desperate", hint: "Feeling you have almost no hope left", syllables: ["des", "per", "ate"], sentence: "He was desperate to find his lost dog before it got dark." },
            { word: "restaurant", hint: "A place where you go to eat meals", syllables: ["res", "tau", "rant"], sentence: "We tried a new restaurant downtown and the food was amazing." },
        ],
    },
    "Level 5": {
        icon: "🔴",
        color: "#d63031",
        words: [
            { word: "psychology", hint: "The study of the mind and behavior", syllables: ["psy", "chol", "o", "gy"], sentence: "She wants to study psychology to understand how people think." },
            { word: "exaggerate", hint: "To make something seem bigger than it is", syllables: ["ex", "ag", "ger", "ate"], sentence: "People often exaggerate how bad the weather is going to be." },
            { word: "phenomenon", hint: "A remarkable or unusual event", syllables: ["phe", "nom", "e", "non"], sentence: "The northern lights are a natural phenomenon that amazes everyone who sees them." },
            { word: "accommodate", hint: "To make room for or adjust to", syllables: ["ac", "com", "mo", "date"], sentence: "The classroom was rearranged to accommodate all thirty-five students comfortably." },
            { word: "mischievous", hint: "Playfully causing trouble (3 syllables, not 4)", syllables: ["mis", "chie", "vous"], sentence: "The mischievous kitten knocked everything off the kitchen counter again." },
            { word: "pronunciation", hint: "How you say a word out loud", syllables: ["pro", "nun", "ci", "a", "tion"], sentence: "Practice the pronunciation of new words by saying them out loud." },
            { word: "refrigerator", hint: "The machine that keeps food cold", syllables: ["re", "frig", "er", "a", "tor"], sentence: "Put the leftover pizza in the refrigerator before it goes bad." },
            { word: "extraordinary", hint: "Very unusual or remarkable", syllables: ["ex", "tra", "or", "di", "nar", "y"], sentence: "The gymnast performed an extraordinary routine that earned a perfect score." },
            { word: "championship", hint: "The final contest to decide a winner", syllables: ["cham", "pi", "on", "ship"], sentence: "Our school basketball team made it to the state championship this year." },
            { word: "independence", hint: "Freedom from control by others", syllables: ["in", "de", "pen", "dence"], sentence: "Learning to cook for yourself is a great step toward independence." },
            { word: "civilization", hint: "An advanced human society", syllables: ["civ", "i", "li", "za", "tion"], sentence: "The ancient Greek civilization made huge contributions to art and science." },
            { word: "communication", hint: "Sharing information with others", syllables: ["com", "mu", "ni", "ca", "tion"], sentence: "Good communication skills help you express your ideas clearly to others." },
            { word: "consequence", hint: "A result of your actions", syllables: ["con", "se", "quence"], sentence: "Every choice you make has a consequence whether good or bad." },
            { word: "environment", hint: "The world and nature around us", syllables: ["en", "vi", "ron", "ment"], sentence: "We should all do our part to protect the environment from pollution." },
            { word: "government", hint: "The group that runs a country", syllables: ["gov", "ern", "ment"], sentence: "The government passed a new law to improve public schools across the state." },
            { word: "immediately", hint: "Right now, without any delay", syllables: ["im", "me", "di", "ate", "ly"], sentence: "The teacher asked us to immediately stop talking and pay attention." },
            { word: "opportunity", hint: "A chance to do something good", syllables: ["op", "por", "tu", "ni", "ty"], sentence: "This internship is a great opportunity to learn real-world job skills." },
            { word: "particularly", hint: "Especially, more than usual", syllables: ["par", "tic", "u", "lar", "ly"], sentence: "The last question on the exam was particularly difficult for everyone." },
            { word: "professional", hint: "Someone expert and paid for their work", syllables: ["pro", "fes", "sion", "al"], sentence: "A professional athlete trains for many hours every single day." },
            { word: "temperature", hint: "How hot or cold something is", syllables: ["tem", "per", "a", "ture"], sentence: "The temperature outside dropped below freezing during the night." },
            { word: "vocabulary", hint: "All the words a person knows", syllables: ["vo", "cab", "u", "lar", "y"], sentence: "Reading for fun is one of the easiest ways to grow your vocabulary." },
            { word: "surveillance", hint: "Close watching of someone or something", syllables: ["sur", "veil", "lance"], sentence: "Security cameras provide surveillance to help keep the building safe." },
            { word: "entrepreneur", hint: "Someone who starts their own business", syllables: ["en", "tre", "pre", "neur"], sentence: "The young entrepreneur started a successful business selling custom sneakers." },
            { word: "embarrassment", hint: "The feeling of being awkward or ashamed", syllables: ["em", "bar", "rass", "ment"], sentence: "Tripping on stage caused her a moment of embarrassment but she laughed it off." },
            { word: "questionnaire", hint: "A form with questions to answer", syllables: ["ques", "tion", "naire"], sentence: "Please fill out this short questionnaire about your favorite school subjects." },
            { word: "autobiography", hint: "A book someone writes about their own life", syllables: ["au", "to", "bi", "og", "ra", "phy"], sentence: "I read an autobiography about a famous scientist who grew up in poverty." },
            { word: "conscientious", hint: "Very careful and thorough about doing things right", syllables: ["con", "sci", "en", "tious"], sentence: "A conscientious student always checks their work before turning it in." },
            { word: "miscellaneous", hint: "A mixture of different types of things", syllables: ["mis", "cel", "la", "ne", "ous"], sentence: "The junk drawer was full of miscellaneous items like tape and batteries." },
            { word: "sophisticated", hint: "Complex, advanced, or worldly", syllables: ["so", "phis", "ti", "cat", "ed"], sentence: "The robot used sophisticated technology to navigate through the maze on its own." },
            { word: "procrastinate", hint: "To keep putting something off until later", syllables: ["pro", "cras", "ti", "nate"], sentence: "If you procrastinate on your homework it will pile up fast." },
        ],
    },

    "FLOSS Words": {
        icon: "🦷",
        color: "#e17055",
        words: [
            // ff words
            { word: "staff", hint: "A group of workers", syllables: ["staff"], sentence: "The staff at the restaurant was very friendly to every customer." },
            { word: "stuff", hint: "Things or belongings", syllables: ["stuff"], sentence: "Please put your stuff in the locker before gym class starts." },
            { word: "bluff", hint: "To pretend you have something you don't", syllables: ["bluff"], sentence: "He tried to bluff his way through the card game but everyone could tell." },
            { word: "cliff", hint: "A steep rock face", syllables: ["cliff"], sentence: "They stood at the edge of the cliff and looked down at the ocean." },
            { word: "scoff", hint: "To mock or laugh at something", syllables: ["scoff"], sentence: "Do not scoff at someone who is trying their best to learn." },
            { word: "sniff", hint: "To breathe in through the nose", syllables: ["sniff"], sentence: "The dog gave the treat a quick sniff before eating it." },
            { word: "stiff", hint: "Not easy to bend", syllables: ["stiff"], sentence: "His neck felt stiff after sleeping in a bad position all night." },
            { word: "scuff", hint: "To scrape or scratch a surface", syllables: ["scuff"], sentence: "Try not to scuff your new shoes on the rough pavement outside." },
            // ll words
            { word: "skill", hint: "An ability you develop with practice", syllables: ["skill"], sentence: "Learning a new skill takes time and patience but it is worth it." },
            { word: "spell", hint: "To write the letters of a word in order", syllables: ["spell"], sentence: "Can you spell the word that the teacher just said out loud?" },
            { word: "drill", hint: "A tool for making holes or to practice", syllables: ["drill"], sentence: "The coach ran a passing drill at the start of every practice." },
            { word: "grill", hint: "A cooking device with flames or heat", syllables: ["grill"], sentence: "Dad likes to grill burgers in the backyard every Saturday." },
            { word: "spill", hint: "To accidentally pour something out", syllables: ["spill"], sentence: "Be careful not to spill your juice on the new carpet." },
            { word: "chill", hint: "To cool down or relax", syllables: ["chill"], sentence: "After the long hike we just wanted to chill and watch a movie." },
            { word: "dwell", hint: "To live in a place or think about something", syllables: ["dwell"], sentence: "Do not dwell on your mistakes because you can always try again." },
            { word: "skull", hint: "The bone that protects the brain", syllables: ["skull"], sentence: "The science class studied a model of the human skull last week." },
            // ss words
            { word: "press", hint: "To push firmly against something", syllables: ["press"], sentence: "You need to press the button to start the machine." },
            { word: "grass", hint: "Green plants covering the ground", syllables: ["grass"], sentence: "The grass in the park was soft and perfect for a picnic." },
            { word: "cross", hint: "To go from one side to the other", syllables: ["cross"], sentence: "Look both ways before you cross the street near the school." },
            { word: "floss", hint: "Thread for cleaning between teeth", syllables: ["floss"], sentence: "The dentist said you should floss your teeth every single day." },
            { word: "glass", hint: "A see-through material used in windows", syllables: ["glass"], sentence: "She drank a cold glass of water after the long run." },
            { word: "dress", hint: "A piece of clothing or to put on clothes", syllables: ["dress"], sentence: "She picked out a nice dress to wear to the school dance." },
            { word: "chess", hint: "A strategy board game with kings and queens", syllables: ["chess"], sentence: "He learned to play chess from watching videos on the internet." },
            { word: "bliss", hint: "Perfect happiness", syllables: ["bliss"], sentence: "Eating ice cream on a hot day is pure bliss." },
            // zz words
            { word: "buzz", hint: "The sound a bee makes", syllables: ["buzz"], sentence: "The buzz of the bees could be heard all around the garden." },
            { word: "fizz", hint: "The bubbles in a drink", syllables: ["fizz"], sentence: "The soda started to fizz when she opened the can too fast." },
            { word: "fuzz", hint: "Soft fine hair or fibers", syllables: ["fuzz"], sentence: "The peach had a thin layer of fuzz on its skin." },
            { word: "jazz", hint: "A type of music with rhythm and soul", syllables: ["jazz"], sentence: "The band played smooth jazz at the downtown music festival." },
            { word: "quiz", hint: "A short test to check what you know", syllables: ["quiz"], sentence: "We have a spelling quiz every Friday morning in class." },
            { word: "whizz", hint: "To move very fast with a buzzing sound", syllables: ["whizz"], sentence: "The cars whizz past the house because the speed limit is too high." },
        ],
    },
};

// Sight words for Speed Drill mode — high-frequency words by level
const SIGHT_WORDS = {
    1: {
        label: "Level 1",
        icon: "🟢",
        color: "#00cec9",
        description: "Common everyday words",
        words: [
            "the", "and", "is", "it", "to", "in", "he", "was", "for", "on",
            "are", "you", "with", "his", "they", "at", "be", "this", "from", "have"
        ],
    },
    2: {
        label: "Level 2",
        icon: "🔵",
        color: "#0984e3",
        description: "Building up to trickier words",
        words: [
            "said", "each", "which", "their", "will", "other", "about", "out", "many", "then",
            "them", "these", "would", "make", "like", "him", "into", "time", "has", "look"
        ],
    },
    3: {
        label: "Level 3",
        icon: "🟡",
        color: "#feca57",
        description: "Challenging sight words",
        words: [
            "because", "different", "through", "thought", "important", "between", "should", "before", "another", "enough",
            "together", "something", "sometimes", "although", "beautiful", "knowledge", "necessary", "beginning", "receive", "believe"
        ],
    },
};

// ===== Phoneme-Grapheme Mapping Data =====
// Organized by category: Digraphs, Blends, Vowel Teams
// Each entry: sound, displayName, spellings array, examples object keyed by spelling

const PHONEME_DATA = {
    "Digraphs": [
        { sound: "sh", displayName: "The SH sound", spellings: ["sh"], examples: { "sh": ["ship", "fish", "wish"] } },
        { sound: "ch", displayName: "The CH sound", spellings: ["ch"], examples: { "ch": ["chip", "much", "lunch"] } },
        { sound: "th", displayName: "The TH sound", spellings: ["th"], examples: { "th": ["thin", "math", "three"] } },
        { sound: "wh", displayName: "The WH sound", spellings: ["wh"], examples: { "wh": ["when", "whale", "white"] } },
        { sound: "ph", displayName: "The PH sound", spellings: ["ph"], examples: { "ph": ["phone", "graph", "photo"] } },
        { sound: "ck", displayName: "The CK sound", spellings: ["ck"], examples: { "ck": ["back", "stick", "clock"] } },
        { sound: "ng", displayName: "The NG sound", spellings: ["ng"], examples: { "ng": ["ring", "song", "long"] } },
    ],
    "Blends": [
        { sound: "bl", displayName: "The BL blend", spellings: ["bl"], examples: { "bl": ["black", "blue"] } },
        { sound: "cr", displayName: "The CR blend", spellings: ["cr"], examples: { "cr": ["cross", "cream"] } },
        { sound: "st", displayName: "The ST blend", spellings: ["st"], examples: { "st": ["star", "stop"] } },
        { sound: "tr", displayName: "The TR blend", spellings: ["tr"], examples: { "tr": ["tree", "trick"] } },
        { sound: "sp", displayName: "The SP blend", spellings: ["sp"], examples: { "sp": ["spin", "spot"] } },
        { sound: "fl", displayName: "The FL blend", spellings: ["fl"], examples: { "fl": ["flag", "fly"] } },
        { sound: "gr", displayName: "The GR blend", spellings: ["gr"], examples: { "gr": ["green", "grip"] } },
        { sound: "br", displayName: "The BR blend", spellings: ["br"], examples: { "br": ["bring", "brave"] } },
        { sound: "pl", displayName: "The PL blend", spellings: ["pl"], examples: { "pl": ["play", "plan"] } },
        { sound: "sn", displayName: "The SN blend", spellings: ["sn"], examples: { "sn": ["snow", "snap"] } },
        { sound: "sw", displayName: "The SW blend", spellings: ["sw"], examples: { "sw": ["swim", "sweet"] } },
        { sound: "str", displayName: "The STR blend", spellings: ["str"], examples: { "str": ["street", "strong"] } },
    ],
    "Vowel Teams": [
        { sound: "long a", displayName: "The long A sound", spellings: ["ai", "ay"], examples: { "ai": ["rain", "train", "wait"], "ay": ["play", "day", "say"] } },
        { sound: "long e", displayName: "The long E sound", spellings: ["ee", "ea"], examples: { "ee": ["tree", "feet", "sleep"], "ea": ["read", "sea", "beach"] } },
        { sound: "long o", displayName: "The long O sound", spellings: ["oa", "ow"], examples: { "oa": ["boat", "road", "coat"], "ow": ["snow", "flow", "grow"] } },
        { sound: "oo", displayName: "The OO sound", spellings: ["oo"], examples: { "oo": ["moon", "food", "soon"] } },
        { sound: "ow", displayName: "The OW/OU sound", spellings: ["ou", "ow"], examples: { "ou": ["out", "house", "loud"], "ow": ["cow", "town", "down"] } },
        { sound: "oy", displayName: "The OY/OI sound", spellings: ["oi", "oy"], examples: { "oi": ["oil", "coin", "join"], "oy": ["boy", "toy", "joy"] } },
    ],
};

// ===== Morpheme Awareness Builder Data =====
// Prefixes, suffixes, and buildable words with meaning breakdowns

const MORPHEME_DATA = {
    prefixes: {
        "un": { meaning: "not", color: "#3b82f6" },
        "re": { meaning: "again", color: "#3b82f6" },
        "pre": { meaning: "before", color: "#3b82f6" },
        "dis": { meaning: "opposite", color: "#3b82f6" },
        "mis": { meaning: "wrong", color: "#3b82f6" },
    },
    suffixes: {
        "ing": { meaning: "doing", color: "#22c55e" },
        "ed": { meaning: "past", color: "#22c55e" },
        "er": { meaning: "one who / more", color: "#22c55e" },
        "est": { meaning: "most", color: "#22c55e" },
        "ful": { meaning: "full of", color: "#22c55e" },
        "less": { meaning: "without", color: "#22c55e" },
        "ness": { meaning: "state of", color: "#22c55e" },
        "able": { meaning: "can be", color: "#22c55e" },
        "tion": { meaning: "act of", color: "#22c55e" },
        "ment": { meaning: "result of", color: "#22c55e" },
    },
    words: [
        { parts: ["un", "kind"], word: "unkind", types: ["prefix", "root"], meanings: ["not", "kind"] },
        { parts: ["re", "play"], word: "replay", types: ["prefix", "root"], meanings: ["again", "play"] },
        { parts: ["re", "build"], word: "rebuild", types: ["prefix", "root"], meanings: ["again", "build"] },
        { parts: ["un", "fair"], word: "unfair", types: ["prefix", "root"], meanings: ["not", "fair"] },
        { parts: ["pre", "heat"], word: "preheat", types: ["prefix", "root"], meanings: ["before", "heat"] },
        { parts: ["dis", "like"], word: "dislike", types: ["prefix", "root"], meanings: ["opposite", "like"] },
        { parts: ["mis", "spell"], word: "misspell", types: ["prefix", "root"], meanings: ["wrong", "spell"] },
        { parts: ["hope", "ful"], word: "hopeful", types: ["root", "suffix"], meanings: ["hope", "full of"] },
        { parts: ["care", "less"], word: "careless", types: ["root", "suffix"], meanings: ["care", "without"] },
        { parts: ["kind", "ness"], word: "kindness", types: ["root", "suffix"], meanings: ["kind", "state of"] },
        { parts: ["teach", "er"], word: "teacher", types: ["root", "suffix"], meanings: ["teach", "one who"] },
        { parts: ["play", "ing"], word: "playing", types: ["root", "suffix"], meanings: ["play", "doing"] },
        { parts: ["tall", "est"], word: "tallest", types: ["root", "suffix"], meanings: ["tall", "most"] },
        { parts: ["enjoy", "ment"], word: "enjoyment", types: ["root", "suffix"], meanings: ["enjoy", "result of"] },
        { parts: ["wash", "able"], word: "washable", types: ["root", "suffix"], meanings: ["wash", "can be"] },
        { parts: ["act", "tion"], word: "action", types: ["root", "suffix"], meanings: ["act", "act of"] },
        { parts: ["re", "start", "ing"], word: "restarting", types: ["prefix", "root", "suffix"], meanings: ["again", "start", "doing"] },
        { parts: ["un", "break", "able"], word: "unbreakable", types: ["prefix", "root", "suffix"], meanings: ["not", "break", "can be"] },
        { parts: ["dis", "agree", "ment"], word: "disagreement", types: ["prefix", "root", "suffix"], meanings: ["opposite", "agree", "result of"] },
        { parts: ["un", "help", "ful"], word: "unhelpful", types: ["prefix", "root", "suffix"], meanings: ["not", "help", "full of"] },
        { parts: ["re", "use", "able"], word: "reusable", types: ["prefix", "root", "suffix"], meanings: ["again", "use", "can be"] },
        { parts: ["pre", "pay", "ment"], word: "prepayment", types: ["prefix", "root", "suffix"], meanings: ["before", "pay", "result of"] },
        { parts: ["mis", "lead", "ing"], word: "misleading", types: ["prefix", "root", "suffix"], meanings: ["wrong", "lead", "doing"] },
        { parts: ["un", "friend", "ly"], word: "unfriendly", types: ["prefix", "root", "suffix"], meanings: ["not", "friend", "like"] },
        { parts: ["care", "ful", "ly"], word: "carefully", types: ["root", "suffix", "suffix"], meanings: ["care", "full of", "in a way"] },
    ],
};

// ===== Dictation Sentences =====
// Orton-Gillingham dictation: hear a sentence, type it word by word.
// 3 levels, 15 sentences each. Difficulty increases with each level.

const DICTATION_SENTENCES = {
    "Level 1": {
        icon: "🟢",
        color: "#00cec9",
        sentences: [
            "The cat is big.",
            "She ran to the park.",
            "He has a red ball.",
            "I like to read books.",
            "The dog sat on the rug.",
            "We went to the store.",
            "My mom made a cake.",
            "The sun is very hot.",
            "He can run so fast.",
            "She has a new pet.",
            "The fish swam in the pond.",
            "I see a big tree.",
            "We played in the yard.",
            "The bird sang a song.",
            "He gave me a hug.",
        ],
    },
    "Level 2": {
        icon: "🔵",
        color: "#0984e3",
        sentences: [
            "The knight knew the right answer.",
            "She could write a beautiful letter.",
            "The phone rang during the night.",
            "He caught the ball with one hand.",
            "They bought a new house last week.",
            "The bridge over the river was old.",
            "She thought the science test was easy.",
            "The whole class laughed at the joke.",
            "He built a castle out of blocks.",
            "The weather changed from warm to cold.",
            "She found a strange shell on the beach.",
            "The island was quiet and peaceful.",
            "He knew the answer before the question.",
            "The rhythm of the song was catchy.",
            "They climbed the mountain in the morning.",
        ],
    },
    "Level 3": {
        icon: "🟡",
        color: "#feca57",
        sentences: [
            "The photographer thought the different rhythm was important.",
            "She received a beautiful beginning to the story.",
            "The environment around the ancient castle was mysterious.",
            "He believed the extraordinary experience changed his perspective.",
            "The temperature dropped significantly throughout the evening hours.",
            "She practiced the pronunciation of every foreign word carefully.",
            "The government announced a necessary change to the schedule.",
            "He recognized the sophisticated technique used in the painting.",
            "The independent restaurant guaranteed a professional experience every time.",
            "She determined that the physical challenge required more preparation.",
            "The atmosphere at the championship was particularly exciting and loud.",
            "He immediately noticed the separate entrance to the building.",
            "The communication between the different departments was essential.",
            "She achieved an extraordinary position through her knowledge and courage.",
            "The calendar showed a Wednesday appointment at the library.",
        ],
    },
};
